language: cpp
env:
  global:
  - sudo apt-get update -qq
  - sudo apt-get install -qq autotools-dev libresiprocate-dev
compiler:
  - gcc
  - clang
script:
  - autoreconf
  - ./configure
  - make
  - make check
